FROM ubuntu:22.04
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        build-essential libcap2-bin sudo python3-minimal && \
    rm -rf /var/lib/apt/lists/*
COPY . /opt/z-privesc
WORKDIR /opt/z-privesc
RUN make static
RUN useradd -m -s /bin/bash pwn
USER pwn
ENTRYPOINT ["/opt/z-privesc/build/bin/z_privesc", "--all", "--json"]
